### ISSUE TITLE
feat: Add `nix.yaml` config to set a Nix development shell to use instead of images

### ISSUE THREAD

**Issue by gabyx** [gabyx/Githooks#177]
It is extremely helpful if we could use Nix devShells to run stuff. 
The functionality would be the same as the one for `images.yaml` which defines images which can be used 

Hook Run Configuration `Version 4`
```yaml
cmd: ...
args: ...
env: ...
image: ...
nix: 
  path: ./tools/nix
  name: "myshell"
  
version: 4 # optional
```

Then `nix develop <base-path>/tools/nix#myshell` will be used, `<base-path>` is relative the shared repo or the current executing one.
