### ISSUE TITLE
feat: Add possibility to pass envs to shared hooks

### ISSUE THREAD

**Issue by gabyx** [gabyx/Githooks#95]
Implement in `.shared.yaml`:
```yaml
envs: 
    hooksA:
      - "OPTION=A"
    hooksB:
      - "OPTION=G"
```
which would inject env variables before running all hooks in namespace `hooksA`and `hooksB`.

With that, the user can customize some shared hooks when using them.
